pipeline {
    agent any

    environment {
        IMAGE_NAME = "mywebsite"
        CONTAINER_NAME = "mywebsite_container"
        DOCKER_REGISTRY = "skuser123"
        DOCKER_PASSWORD= "Skuser@12345"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/skuser123/EcommerceWeb.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'skuser123', variable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u ${DOCKER_REGISTRY} --password-stdin"
                        sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                script {
                    sh "docker stop ${CONTAINER_NAME} || true"
                    sh "docker rm ${CONTAINER_NAME} || true"
                    sh "docker pull ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
                    sh "docker run -d -p 80:80 --name ${CONTAINER_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed."
        }
    }
}
